# This is the main configuration file of your Dancer2 app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "App"

# The default layout to use for your application (located in
# views/layouts/main.tt)
#layout: "main"
layout: "bootstrap"

# when the charset is set to UTF-8 Dancer2 will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
  template:
    template_toolkit:
      encoding:  'utf8'
      INCLUDE_PATH: 'views'
      start_tag: '<%'
      end_tag:   '%>'

plugins:
   Database:
      driver: 'mysql'
      database: ''
      host: '127.0.0.1'
      port: 3306
      username: ''
      password: ''
      connection_check_threshold: 10
      dbi_params:
             RaiseError: 1
             AutoCommit: 1
      on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
      log_queries: 1
      #handle_class: 'My::Super::Sexy::Database::Handle'
